[package]
name = "zsh-system"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[build-dependencies]
bindgen = "0.72.1"

[features]
default = ["5-9"]
5-9 = []

[dependencies]
